/**
 * Official brand logos held locally under public/media/brands.
 *
 * GENERATED by scripts/fetch-brand-logos.ts — do not edit by hand. Re-run the
 * script to add a brand or refresh an asset; provenance for every file is in
 * public/media/brands/logo-provenance.json.
 *
 * `brands.logo_url` in the database is the source of truth and wins whenever
 * it is set. This map is the fallback for rows that predate the column being
 * populated, and it is also what supplies the intrinsic size and the optical
 * scale — neither of which the database column carries.
 */

export type BrandLogo = {
  src: string;
  width: number;
  height: number;
  /**
   * Height relative to the logo stage, 0–1, equalising letterform size across
   * marks whose artwork includes very different amounts of surrounding
   * material. See the note in scripts/fetch-brand-logos.ts.
   */
  opticalScale: number;
};

const BRAND_LOGOS: Record<string, BrandLogo> = {
  cerave: {
    src: '/media/brands/cerave.svg',
    width: 330,
    height: 114,
    opticalScale: 1,
  },
  cetaphil: {
    src: '/media/brands/cetaphil.png',
    width: 1100,
    height: 532,
    opticalScale: 0.85,
  },
  cosrx: {
    src: '/media/brands/cosrx.png',
    width: 129,
    height: 27,
    opticalScale: 0.5,
  },
  eucerin: {
    src: '/media/brands/eucerin.svg',
    width: 209,
    height: 78,
    opticalScale: 0.78,
  },
  'ferrero-rocher': {
    src: '/media/brands/ferrero-rocher.svg',
    width: 117,
    height: 50,
    opticalScale: 0.9,
  },
  garnier: {
    src: '/media/brands/garnier.png',
    width: 240,
    height: 60,
    opticalScale: 0.72,
  },
  'la-roche-posay': {
    src: '/media/brands/la-roche-posay.png',
    width: 200,
    height: 51,
    opticalScale: 0.9,
  },
  purito: {
    src: '/media/brands/purito.svg',
    width: 206,
    height: 60,
    opticalScale: 0.5,
  },
  revuele: {
    src: '/media/brands/revuele.svg',
    width: 227,
    height: 76,
    opticalScale: 0.85,
  },
  skin1004: {
    src: '/media/brands/skin1004.png',
    width: 300,
    height: 46,
    opticalScale: 1,
  },
  'the-ordinary': {
    src: '/media/brands/the-ordinary.svg',
    width: 84,
    height: 31,
    opticalScale: 0.92,
  },
};

/** The held logo for a brand slug, or null when we do not have one. */
export function brandLogo(slug: string): BrandLogo | null {
  return BRAND_LOGOS[slug] ?? null;
}
